// TypeScript interfaces matching the JSON schemas generated by 07_generate_json.py

export interface RankingEntry {
  state: string;
  slug: string;
  region: string;
  rank: number;
  rank_change: number | null;
  composite_score: number;
  gst_zscore: number | null;
  electricity_zscore: number | null;
  credit_zscore: number | null;
  epfo_zscore: number | null;
  n_components: number;
}

export interface RankingsData {
  fiscal_year: string;
  generated_at: string;
  count: number;
  rankings: RankingEntry[];
}

export interface ComponentInfo {
  name: string;
  column: string;
  unit: string;
  type: string;
  frequency: string;
  source: string;
  license?: string;
}

export interface MetadataData {
  generated_at: string;
  methodology: {
    name: string;
    version: string;
    description: string;
    normalization: string;
    weights: string;
    min_components: number;
    components: ComponentInfo[];
  };
  data_coverage: {
    fiscal_years: string[];
    latest_fy: string;
    states_count: number;
    states_with_4_components: number;
  };
}

export interface AnnualTrendEntry {
  state: string;
  fiscal_years: string[];
  composite_score: (number | null)[];
  rank: (number | null)[];
  gst_total: (number | null)[];
  electricity_mu: (number | null)[];
  bank_credit_yoy: (number | null)[];
  epfo_payroll: (number | null)[];
}

export interface MonthlyTrendEntry {
  state: string;
  months: string[];
  gst_total: (number | null)[];
  electricity_mu: (number | null)[];
  gst_zscore: (number | null)[];
  electricity_zscore: (number | null)[];
}

export interface TrendsData {
  generated_at: string;
  fiscal_years: string[];
  annual: Record<string, AnnualTrendEntry>;
  monthly: Record<string, MonthlyTrendEntry>;
}

export interface PeerState {
  state: string;
  slug: string;
  composite_score: number;
  rank: number | null;
}

export interface StateDetail {
  state: string;
  slug: string;
  region: string;
  annual: {
    fiscal_years: string[];
    composite_score: (number | null)[];
    rank: (number | null)[];
    rank_change: (number | null)[];
    gst_total: (number | null)[];
    electricity_mu: (number | null)[];
    bank_credit_yoy: (number | null)[];
    epfo_payroll: (number | null)[];
    gst_zscore: (number | null)[];
    electricity_zscore: (number | null)[];
    credit_zscore: (number | null)[];
    epfo_zscore: (number | null)[];
    n_components: number[];
  };
  monthly: {
    months: string[];
    gst_total: (number | null)[];
    electricity_mu: (number | null)[];
    gst_zscore: (number | null)[];
    electricity_zscore: (number | null)[];
  };
  peers: PeerState[];
  insights?: StateInsights;
}

// Recharts-friendly data point for trend charts
export interface TrendChartPoint {
  fiscal_year: string;
  [slug: string]: string | number | null;
}

// --- Insights Types ---

export interface KeyFinding {
  type: string;
  title: string;
  detail: string;
  states: string[];
}

export interface CorrelationEntry {
  r: number | null;
  p: number | null;
  n: number;
  note?: string;
}

export interface CorrelationData {
  latest_fy: string;
  note: string;
  gst_gsdp: CorrelationEntry;
  electricity_gsdp: CorrelationEntry;
  credit_gsdp: CorrelationEntry;
  epfo_gsdp: CorrelationEntry;
  composite_gsdp: CorrelationEntry;
}

export interface GrowthRankingEntry {
  state: string;
  slug: string;
  rank: number | null;
  momentum_tier: string | null;
  rank_momentum_3yr: number | null;
  gst_yoy_pct: number | null;
  elec_yoy_pct: number | null;
  credit_yoy_pct: number | null;
  epfo_yoy_pct: number | null;
}

export interface GsdpComparisonEntry {
  state: string;
  slug: string;
  index_rank: number | null;
  gsdp_rank: number;
  rank_gap: number | null;
  gap_label: string | null;
}

export interface CovidRecoveryEntry {
  state: string;
  slug: string;
  covid_dip: number;
  recovery_speed: number | null;
  recovery_fy: string | null;
  never_recovered: boolean;
  pre_covid_declining: boolean;
}

export interface ComponentDiagnostic {
  strongest: string | null;
  weakest: string | null;
  divergence_score: number | null;
  diagnostic: string | null;
  brap_category: string | null;
}

export interface InsightsData {
  generated_at: string;
  latest_fy: string;
  key_findings: KeyFinding[];
  correlations: CorrelationData;
  growth_rankings: GrowthRankingEntry[];
  gsdp_comparison: GsdpComparisonEntry[];
  covid_recovery: CovidRecoveryEntry[];
  component_diagnostics: Record<string, ComponentDiagnostic>;
}

// --- Regression Types ---

export interface CoefficientInfo {
  coef: number;
  se: number;
  t: number;
  p: number;
  ci_low: number;
  ci_high: number;
  beta?: number;
  robust_se?: number;
  robust_t?: number;
  robust_p?: number;
}

export interface RegressionDiagnostics {
  vif: Record<string, number> | string;
  vif_warning?: string;
  breusch_pagan_stat?: number;
  breusch_pagan_p: number | string;
  heteroscedasticity_warning?: string;
  robust_se_used?: boolean;
  shapiro_wilk_stat?: number;
  shapiro_wilk_p: number | string;
  normality_warning?: string;
  cooks_distance_threshold?: number;
  cooks_distance_flagged: string[];
  durbin_watson: number | null;
}

export interface CrossSectionalResult {
  n: number;
  r_squared: number;
  adj_r_squared: number;
  f_statistic: number;
  f_pvalue: number;
  degrees_of_freedom: { residual: number; model: number };
  coefficients: Record<string, CoefficientInfo>;
  diagnostics: RegressionDiagnostics;
  without_maharashtra?: {
    n: number;
    r_squared: number;
    adj_r_squared?: number;
    f_statistic?: number;
    f_pvalue?: number;
    note?: string;
  };
}

export interface StepwiseEntry {
  r_squared: number;
  adj_r_squared: number;
  aic: number;
  bic: number;
  delta_r2?: number;
  partial_f?: number;
  partial_f_p?: number;
}

export interface RegressionData {
  generated_at: string;
  note: string;
  latest_fy_with_gsdp?: string;
  skipped?: boolean;
  reason?: string;
  cross_sectional?: Record<string, CrossSectionalResult>;
  stepwise?: Record<string, StepwiseEntry>;
  pooled_panel?: {
    n_observations?: number;
    n_years?: number;
    r_squared?: number;
    adj_r_squared?: number;
    f_statistic?: number;
    f_pvalue?: number;
    note?: string;
    skipped?: boolean;
    reason?: string;
  };
  interpretation?: string;
}

// --- Enhanced State Detail with Insights ---

export interface StateInsights {
  diagnostic_text: string | null;
  strongest_component: string | null;
  weakest_component: string | null;
  divergence_score: number | null;
  momentum_tier: string | null;
  rank_momentum_3yr: number | null;
  gsdp_rank: number | null;
  rank_gap: number | null;
  gap_label: string | null;
  brap_category: string | null;
  covid_dip: number | null;
  recovery_speed: number | null;
  gst_yoy_pct: number | null;
  elec_yoy_pct: number | null;
  credit_yoy_pct: number | null;
  epfo_yoy_pct: number | null;
}

// Extended RankingEntry with insight fields
export interface EnrichedRankingEntry extends RankingEntry {
  momentum_tier?: string | null;
  gsdp_rank?: number | null;
  rank_gap?: number | null;
  brap_category?: string | null;
}

// --- Electricity Analysis Types ---

export interface ElectricityMonthlyGrowth {
  month: string;
  yoy_pct: number;
}

export interface ElectricitySeasonalityPoint {
  month: number;
  index: number;
}

export interface StateElectricityProfile {
  intensity_mu_per_crore: number | null;
  national_share_pct: number | null;
  elasticity: number | null;
  elasticity_label: string | null;
  bivariate_residual_crore: number | null;
  residual_label: string | null;
  volatility_cov: number | null;
  monthly_growth: ElectricityMonthlyGrowth[];
  seasonality_index: ElectricitySeasonalityPoint[];
}

export interface ElectricityIntensityRanking {
  state: string;
  slug: string;
  intensity: number;
  gsdp_crore: number;
  electricity_mu: number;
}

export interface ElectricityElasticityRanking {
  state: string;
  slug: string;
  elasticity: number;
  label: string;
}

export interface ElectricityScatterPoint {
  state: string;
  slug: string;
  electricity_mu: number;
  gsdp_crore: number;
  elasticity_label: string | null;
  residual_crore: number | null;
}

export interface ElectricityData {
  generated_at: string;
  national_summary: {
    total_mu_latest_fy: number;
    yoy_growth_pct: number;
    gsdp_correlation_r: number;
    latest_fy: string;
  };
  state_profiles: Record<string, StateElectricityProfile>;
  rankings_by_intensity: ElectricityIntensityRanking[];
  rankings_by_elasticity: ElectricityElasticityRanking[];
  electricity_vs_gsdp_scatter: ElectricityScatterPoint[];
  electricity_vs_gsdp_regression: {
    r_squared: number;
    n: number;
    coef: number;
    intercept: number;
    latest_fy: string;
  };
}

// --- Enhanced Insights Types ---

export interface GapExplanationEntry {
  state: string;
  slug: string;
  index_rank: number | null;
  gsdp_rank: number | null;
  rank_gap: number | null;
  direction: string;
  explanation: string;
  key_drivers: string[];
  key_drags: string[];
  strongest_component: string | null;
  weakest_component: string | null;
}

export interface GapExplanationsData {
  latest_fy: string;
  all: Record<string, GapExplanationEntry>;
  top_outperformers: string[];
  top_underperformers: string[];
}

export interface RegionSummary {
  mean_composite: number;
  median_composite: number;
  n_states: number;
  states: string[];
  best_state: string;
  worst_state: string;
  mean_gsdp_rank?: number;
  trend?: string;
}

export interface RegionalTrendPoint {
  fiscal_year: string;
  mean_composite: number;
  n_states: number;
}

export interface RegionalAnalysisData {
  latest_fy: string;
  regions: Record<string, RegionSummary>;
  trends: Record<string, RegionalTrendPoint[]>;
}

export interface PanelFEResult {
  n: number;
  n_states: number;
  n_years: number;
  within_r_squared: number;
  between_r_squared: number | null;
  overall_r_squared: number;
  coefficients: Record<string, { coef: number; se: number; t: number; p: number }>;
  hausman_test?: { stat?: number; p?: number; preferred?: string; note?: string };
  note: string;
  skipped?: boolean;
}

export interface LogLogResult {
  cross_sectional?: {
    n: number;
    fiscal_year: string;
    r_squared: number;
    adj_r_squared: number;
    elasticities: Record<string, { elasticity: number; p: number }>;
    note: string;
  };
  panel?: {
    n: number;
    n_years: number;
    r_squared: number;
    elasticities: Record<string, { elasticity: number; p: number }>;
    note: string;
  };
  skipped?: boolean;
}

export interface LaggedResult {
  n: number;
  n_states: number;
  lag_years: number;
  simple_correlation: { r: number; p: number };
  panel_fe: { electricity_growth_coef: number; se: number; t: number; p: number };
  interpretation: string;
  note: string;
  skipped?: boolean;
}

export interface PCAResult {
  n: number;
  fiscal_year: string;
  pc1_loadings: Record<string, number>;
  pc1_variance_explained_pct: number;
  all_variance_explained_pct?: number[];
  implied_weights: Record<string, number>;
  rank_correlation_with_equal_weights: number;
  rank_correlation_p: number;
  interpretation: string;
  skipped?: boolean;
}

// Extended RegressionData with new analysis types
export interface EnhancedRegressionData extends RegressionData {
  panel_fe?: PanelFEResult;
  log_log?: LogLogResult;
  lagged?: LaggedResult;
  pca?: PCAResult;
}

// Extended InsightsData with new sections
export interface EnhancedInsightsData extends InsightsData {
  gap_explanations?: GapExplanationsData;
  regional_analysis?: RegionalAnalysisData;
}

// Extended StateDetail with electricity + gap explanation
export interface EnhancedStateDetail extends StateDetail {
  electricity?: {
    intensity_mu_per_crore: number | null;
    national_share_pct: number | null;
    elasticity: number | null;
    elasticity_label: string | null;
    volatility_cov: number | null;
  };
  gap_explanation?: {
    direction: string;
    explanation: string;
    key_drivers: string[];
    key_drags: string[];
  };
}
