// TypeScript interfaces matching the JSON schemas generated by 07_generate_json.py

export interface RankingEntry {
  state: string;
  slug: string;
  region: string;
  rank: number;
  rank_change: number | null;
  composite_score: number;
  gst_zscore: number | null;
  electricity_zscore: number | null;
  credit_zscore: number | null;
  epfo_zscore: number | null;
  n_components: number;
}

export interface RankingsData {
  fiscal_year: string;
  generated_at: string;
  count: number;
  rankings: RankingEntry[];
}

export interface ComponentInfo {
  name: string;
  column: string;
  unit: string;
  type: string;
  frequency: string;
  source: string;
  license?: string;
}

export interface MetadataData {
  generated_at: string;
  methodology: {
    name: string;
    version: string;
    description: string;
    normalization: string;
    weights: string;
    min_components: number;
    components: ComponentInfo[];
  };
  data_coverage: {
    fiscal_years: string[];
    latest_fy: string;
    states_count: number;
    states_with_4_components: number;
  };
}

export interface AnnualTrendEntry {
  state: string;
  fiscal_years: string[];
  composite_score: (number | null)[];
  rank: (number | null)[];
  gst_total: (number | null)[];
  electricity_mu: (number | null)[];
  bank_credit_yoy: (number | null)[];
  epfo_payroll: (number | null)[];
}

export interface MonthlyTrendEntry {
  state: string;
  months: string[];
  gst_total: (number | null)[];
  electricity_mu: (number | null)[];
  gst_zscore: (number | null)[];
  electricity_zscore: (number | null)[];
}

export interface TrendsData {
  generated_at: string;
  fiscal_years: string[];
  annual: Record<string, AnnualTrendEntry>;
  monthly: Record<string, MonthlyTrendEntry>;
}

export interface PeerState {
  state: string;
  slug: string;
  composite_score: number;
  rank: number | null;
}

export interface StateDetail {
  state: string;
  slug: string;
  region: string;
  annual: {
    fiscal_years: string[];
    composite_score: (number | null)[];
    rank: (number | null)[];
    rank_change: (number | null)[];
    gst_total: (number | null)[];
    electricity_mu: (number | null)[];
    bank_credit_yoy: (number | null)[];
    epfo_payroll: (number | null)[];
    gst_zscore: (number | null)[];
    electricity_zscore: (number | null)[];
    credit_zscore: (number | null)[];
    epfo_zscore: (number | null)[];
    n_components: number[];
  };
  monthly: {
    months: string[];
    gst_total: (number | null)[];
    electricity_mu: (number | null)[];
    gst_zscore: (number | null)[];
    electricity_zscore: (number | null)[];
  };
  peers: PeerState[];
}

// Recharts-friendly data point for trend charts
export interface TrendChartPoint {
  fiscal_year: string;
  [slug: string]: string | number | null;
}
